name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cache for Gradle
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Assemble debug
        run: ./gradlew --no-daemon assembleDebug

      - name: Get project name
        id: get_project_name
        run: |
          PROJECT_NAME=$(basename $GITHUB_REPOSITORY)
          echo "PROJECT_NAME=$PROJECT_NAME" | tee -a $GITHUB_ENV

      - name: Get short revision
        id: get_revision
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" | tee -a $GITHUB_ENV

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-debug-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-debug.apk

